# Generated by rust2rpm 28
%bcond check 1

%global crate ptools
%global cargo_install_lib 0

Name:           rust-ptools
Version:        0.2.2
Release:        %autorelease
Summary:        Utilities for inspecting Linux processes

License:        Apache-2.0
URL:            https://github.com/basil/ptools
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Utilities for inspecting Linux processes.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# Apache-2.0
# Apache-2.0 OR MIT
# MIT
# MIT OR Apache-2.0
License:        Apache-2.0 AND MIT
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/pargs
%{_bindir}/penv
%{_bindir}/pfiles
%{_bindir}/ptree

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
